apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: influxdb
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana       # Name of the chart
      version: 8.6.4           # Specific version of the chart
      sourceRef:
        kind: HelmRepository
        name: influxdb-helm-repo
        namespace: influxdb
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    disableHooks: true
    force: true
    recreate: true
    cleanupOnFail: true
    timeout: "5m"
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    service:
      type: LoadBalancer         # Example: Use LoadBalancer for external access
    metrics:
      enabled: true              # Example: Enable Prometheus metrics
