apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: influxdb-helm-repo
  namespace: influxdb
spec:
  interval: 1m
  url: https://github.com/Mars-Incorporated/az2-mdm-pn/tree/main/kkm/apps/influxdb
  
